version: "3"
services:
  jupyterlab:
    build:
      context: .
      dockerfile: Dockerfile.dev
    user: root
    ports:
      - "8889:8888"
    volumes:
      - "./:/home/jovyan/work"
    environment:
      GRANT_SUDO: "yes"
      JUPYTER_ENABLE_LAB: 1
    command: start.sh jupyter lab
